name: build
on:
  workflow_dispatch:
  push:

jobs:
  deploy_nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          repositories: trnila/test_infra
      - uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: trnila/test_infra
          ref: main
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
          gh auth setup-git
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - run: sed -i -E "s#ghcr.io/trnila/assistant:[^\"]+#ghcr.io/trnila/assistant:${{ github.sha }}#g" configuration.nix
      - run: git add configuration.nix
      - run: git commit -m "Update assistant container to ${{ github.sha }}"
      - run: git push
